[tool.poetry]
name = "perconet"
version = "0.1.0"
description = "Analyze percolation properties of periodic networks"
authors = ["Chiara Raffaelli, Wouter G. Ellenbroek"]
license = "BSD-3"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
numpy = "^1.21.4"
sympy = "^1.9"

[tool.poetry.dev-dependencies]
Sphinx = "^4.3.0"
sphinx-rtd-theme = "^1.0.0"
flake8 = "^4.0.1"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
